version: '3'

services:
  vulnman-web:
    image: ghcr.io/vulnman/vulnman:latest
    volumes:
      - './volumes/vulnman/conf:/app/vulnman/conf'
      - './volumes/vulnman/data/uploads:/app/uploads'
      - './volumes/vulnman/static:/app/static_files'
      - './volumes/vulnman/data/resources:/app/resources'
    environment:
      DJANGO_SUPERUSER_PASSWORD: dontusethispassword
      DJANGO_SUPERUSER_USERNAME: vulnmanadmin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      VULNMAN_DB_USER: vulnman_db_user
      VULNMAN_DB_PASSWORD: dontusethispassword
      VULNMAN_CSRF_TRUSTED_ORIGINS: https://localhost,https://127.0.0.1
    depends_on:
      - db

  worker:
    image: ghcr.io/vulnman/vulnman:latest
    entrypoint: python manage.py qcluster
    volumes:
      - './volumes/vulnman/conf:/app/vulnman/conf'
      - './volumes/vulnman/data/resources:/app/resources'
    depends_on:
      - redis
      - vulnman-web

  db:
    image: postgres:alpine
    volumes:
      - './volumes/vulnman/db:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: dontusethispassword
      POSTGRES_USER: vulnman_db_user
      POSTGRES_DB: vulnman

  redis:
    image: "redis:alpine"

  nginx:
    image: ghcr.io/vulnman/docker-vulnman-nginx:master
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    volumes:
      - './volumes/vulnman/nginx/config:/config'
      - './volumes/vulnman/static:/config/www/static'
      - './volumes/vulnman/data/uploads:/config/www/uploads'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - vulnman-web
