version: '3'

services:
  vulnman-web:
    image: ghcr.io/vulnman/vulnman:latest
    volumes:
      - '/tmp/volumes/vulnman/conf:/app/vulnman/conf'
      - '/tmp/volumes/vulnman/static:/app/static_files'
    environment:
      DJANGO_SUPERUSER_PASSWORD: dontusethispassword
      DJANGO_SUPERUSER_USERNAME: vulnmanadmin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
    depends_on:
      - db

  celery:
    image: ghcr.io/vulnman/vulnman:latest
    entrypoint: celery -A vulnman worker -l INFO
    volumes:
      - '/tmp/volumes/vulnman/conf:/app/vulnman/conf'
      - '/tmp/volumes/vulnman/static:/app/static_files'
    depends_on:
      - redis

  db:
    image: postgres:alpine
    volumes:
      - '/tmp/volumes/vulnman/db:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: dontusethispassword
      POSTGRES_USER: vulnman_db_user
      POSTGRES_DB: vulnman

  redis:
    image: "redis:alpine"

  nginx:
    image: ghcr.io/vulnman/docker-vulnman-nginx:master
    container_name: nginx
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      VULNMAN_DB_USER: vulnman_db_user
      VULNMAN_DB_PASSWORD: dontusethispassword
      VULNMAN_CSRF_TRUSTED_ORIGINS: https://localhost
    volumes:
      - '/tmp/volumes/nginx/config:/config'
      - '/tmp/volumes/vulnman/static:/config/www/static'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - vulnman-web
