name: Task
description: 'Anything that is not a bug or enhancement request'
labels: ["T: task", "P: default"]


body:
  - type: textarea
    id: the-summary
    attributes:
      label: Give a brief summary
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: If there are some information you want to share about the issue
    validations:
      required: false