name: Move new issues into Triage

on:
  issues:
    types: [opened, labeled]

jobs:
  new-issue-project-triage:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Issue Triage
          column: Needs triage
          repo-token: ${{ secrets.VULNMAN_ISSUE_TOKEN }}
  move-by-priority-label:
    if: "${{ github.event.label.name == 'P: major' }}"
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Issue Triage
          column: High priority
          repo-token: ${{ secrets.VULNMAN_ISSUE_TOKEN }}
